/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 15 23:24:50 EST 2017
 */

package main;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import java.awt.HeadlessException;
import java.util.ArrayList;

import javax.swing.DebugGraphics;
import javax.swing.JPanel;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = false, useJEE = true) 
public class DrawGUI_ESTest extends DrawGUI_ESTest_scaffolding {

  @Test(timeout = 100000)
  public void test0()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      DrawGUI drawGUI0 = new DrawGUI(arrayList0, 0);
      DrawGUI.animate(drawGUI0, drawGUI0);
      assertEquals(0, DrawGUI.num_floors);
  }

  @Test(timeout = 100000)
  public void test1()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      // Undeclared exception!
      try { 
        DrawGUI.initGraphics(arrayList0, (-1));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.RequestListener", e);
      }
  }

  @Test(timeout = 100000)
  public void test2()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      // Undeclared exception!
      try { 
        DrawGUI.initGraphics(arrayList0, 0);
        fail("Expecting exception: HeadlessException");
      
      } catch(HeadlessException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.awt.GraphicsEnvironment", e);
      }
  }

  @Test(timeout = 100000)
  public void test3()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      DrawGUI drawGUI0 = new DrawGUI(arrayList0, (-1));
      // Undeclared exception!
      try { 
        DrawGUI.extButtons(drawGUI0, (RequestListener) null);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.DrawGUI", e);
      }
  }

  @Test(timeout = 100000)
  public void test4()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      Elevator elevator0 = new Elevator(0);
      arrayList0.add(elevator0);
      DrawGUI drawGUI0 = new DrawGUI(arrayList0, 0);
      RequestListener requestListener0 = new RequestListener(drawGUI0.elevators, 0);
      DrawGUI.intButtons(drawGUI0, requestListener0);
      assertEquals(0, DrawGUI.num_floors);
  }

  @Test(timeout = 100000)
  public void test5()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      DrawGUI drawGUI0 = new DrawGUI(arrayList0, 2);
      RequestListener requestListener0 = new RequestListener(drawGUI0.elevators, 0);
      DrawGUI.extButtons(drawGUI0, requestListener0);
      assertEquals(2, DrawGUI.num_floors);
  }

  @Test(timeout = 100000)
  public void test6()  throws Throwable  {
      // Undeclared exception!
      try { 
        DrawGUI.animate((JPanel) null, (JPanel) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.DrawGUI", e);
      }
  }

  @Test(timeout = 100000)
  public void test7()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      DrawGUI drawGUI0 = new DrawGUI(arrayList0, 0);
      DebugGraphics debugGraphics0 = new DebugGraphics();
      // Undeclared exception!
      try { 
        drawGUI0.paintComponent(debugGraphics0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.swing.DebugGraphics", e);
      }
  }

  @Test(timeout = 100000)
  public void test8()  throws Throwable  {
      // Undeclared exception!
      try { 
        DrawGUI.initGraphics((ArrayList<Elevator>) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.RequestListener", e);
      }
  }
}
