/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 15 23:29:15 EST 2017
 */

package main;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.fail;

import java.util.TreeSet;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = false, useJEE = true) 
public class Elevator_ESTest extends Elevator_ESTest_scaffolding {

  @Test(timeout = 100000)
  public void test00()  throws Throwable  {
      Elevator elevator0 = new Elevator((-3074));
      elevator0.closeDoors();
      elevator0.setRequestSet((TreeSet<Double>) null);
      elevator0.setCurrentFloor((-1.0));
      elevator0.setInternalEnabled(false);
      elevator0.setCurrentFloor(0.0);
      Doors doors0 = Doors.CLOSED;
      elevator0.openDoors();
      Direction direction0 = Direction.UP;
      elevator0.setDirection(direction0);
      elevator0.setDoorStatus(doors0);
      elevator0.getMotorThread();
      Direction direction1 = Direction.DOWN;
      elevator0.setDirection(direction1);
      elevator0.setDirection(direction0);
      // Undeclared exception!
      try { 
        elevator0.serveFloor((-1.0));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Elevator", e);
      }
  }

  @Test(timeout = 100000)
  public void test01()  throws Throwable  {
      Elevator elevator0 = new Elevator(1);
      Direction direction0 = Direction.DOWN;
      elevator0.setDirection(direction0);
      elevator0.getInternalEnabled();
      Direction direction1 = Direction.UP;
      elevator0.setDirection(direction1);
      TreeSet<Double> treeSet0 = new TreeSet<Double>();
      Double double0 = new Double(1);
      Double.min((-1094.3630036295), 1);
      treeSet0.add(double0);
      elevator0.setRequestSet(treeSet0);
      elevator0.setInternalEnabled(false);
      elevator0.getDoorStatus();
      elevator0.getMotorThread();
      elevator0.setMotorThread((Thread) null);
      // Undeclared exception!
      try { 
        elevator0.serveFloor(0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Elevator", e);
      }
  }

  @Test(timeout = 100000)
  public void test02()  throws Throwable  {
      Elevator elevator0 = new Elevator(0);
      elevator0.setDoorStatus(Doors.OPENED);
      elevator0.setDoorSlide(4);
      elevator0.closeDoors();
      elevator0.getDoorSize();
  }

  @Test(timeout = 100000)
  public void test03()  throws Throwable  {
      Elevator elevator0 = new Elevator(1035);
      Doors doors0 = Doors.OPENING;
      elevator0.setDoorStatus(doors0);
      elevator0.setMotorThread((Thread) null);
      elevator0.setMotorThread((Thread) null);
      elevator0.getName();
      elevator0.getInternalEnabled();
      // Undeclared exception!
      try { 
        elevator0.serveFloor(1.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Elevator", e);
      }
  }

  @Test(timeout = 100000)
  public void test04()  throws Throwable  {
      Elevator elevator0 = new Elevator((-1104));
      elevator0.setDoorSize((-1104));
      elevator0.getMotorThread();
      elevator0.setMotorThread((Thread) null);
      elevator0.getName();
  }

  @Test(timeout = 100000)
  public void test05()  throws Throwable  {
      Elevator elevator0 = new Elevator((-1901));
      TreeSet<Double> treeSet0 = elevator0.getRequestSet();
      Double double0 = new Double((-1901));
      treeSet0.add(double0);
      Double double1 = new Double((-3271.36481));
      Double.sum(3072.4000612, (-1901));
      treeSet0.add(double1);
      elevator0.setRequestSet(treeSet0);
      elevator0.openDoors();
      elevator0.setDoorSlide(1224);
      elevator0.closeDoors();
      elevator0.getInternalEnabled();
      elevator0.getMotorThread();
      elevator0.getDirection();
  }

  @Test(timeout = 100000)
  public void test06()  throws Throwable  {
      Elevator elevator0 = new Elevator(1483);
      Direction direction0 = Direction.UP;
      elevator0.setDirection(direction0);
      // Undeclared exception!
      try { 
        elevator0.serveFloor(0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Elevator", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Elevator elevator0 = new Elevator(2589);
      elevator0.setInternalEnabled(false);
      elevator0.setCurrentFloor(0.0);
      elevator0.setCurrentFloor(353.947681273);
      Elevator elevator1 = new Elevator(2589);
      elevator1.getMotorThread();
      elevator0.setMotorThread((Thread) null);
      elevator0.setDoorSlide(1);
      Doors doors0 = Doors.CLOSED;
      elevator0.setDoorStatus(doors0);
      // Undeclared exception!
      try { 
        elevator0.serveFloorInt(353.947681273);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Elevator", e);
      }
  }

  @Test(timeout = 100000)
  public void test08()  throws Throwable  {
      Elevator elevator0 = new Elevator(1122);
      elevator0.getMotorThread();
      elevator0.closeDoors();
      elevator0.setMotorThread((Thread) null);
      elevator0.setCurrentFloor(1122);
      // Undeclared exception!
      try { 
        elevator0.serveFloorInt(1761.59);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Elevator", e);
      }
  }

  @Test(timeout = 100000)
  public void test09()  throws Throwable  {
      Elevator elevator0 = new Elevator(0);
      elevator0.openDoors();
      elevator0.setDoorSlide(0);
      elevator0.getCurrentFloor();
      // Undeclared exception!
      try { 
        elevator0.serveFloorInt(0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Elevator", e);
      }
  }

  @Test(timeout = 100000)
  public void test10()  throws Throwable  {
      Elevator elevator0 = new Elevator((-1));
      elevator0.getDirection();
  }

  @Test(timeout = 100000)
  public void test11()  throws Throwable  {
      Elevator elevator0 = new Elevator(0);
      Direction direction0 = Direction.DOWN;
      elevator0.openDoors();
      elevator0.setDirection(direction0);
      elevator0.setDirection(direction0);
      elevator0.setInternalEnabled(true);
      TreeSet<Double> treeSet0 = elevator0.getRequestSet();
      // Undeclared exception!
      try { 
        treeSet0.toArray((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.AbstractCollection", e);
      }
  }
}
