/*
 * This file was automatically generated by EvoSuite
 * Fri Dec 15 23:33:43 EST 2017
 */

package main;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.fail;

import java.awt.event.ActionEvent;
import java.util.ArrayList;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = false, useJEE = true) 
public class RequestListener_ESTest extends RequestListener_ESTest_scaffolding {

  @Test(timeout = 100000)
  public void test0()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      Elevator elevator0 = new Elevator(0);
      RequestListener requestListener0 = new RequestListener(arrayList0, 0);
      // Undeclared exception!
      try { 
        requestListener0.internalCall(1, elevator0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("main.RequestListener", e);
      }
  }

  @Test(timeout = 100000)
  public void test1()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      RequestListener requestListener0 = new RequestListener(arrayList0, 2);
      Elevator elevator0 = new Elevator(0);
      arrayList0.add(elevator0);
      requestListener0.run();
  }

  @Test(timeout = 100000)
  public void test2()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      Elevator elevator0 = new Elevator(0);
      Direction direction0 = Direction.DOWN;
      arrayList0.add(elevator0);
      RequestListener requestListener0 = new RequestListener(arrayList0, 1);
      // Undeclared exception!
      try { 
        requestListener0.externalCall(0, direction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.Elevator", e);
      }
  }

  @Test(timeout = 100000)
  public void test3()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      RequestListener requestListener0 = new RequestListener(arrayList0, 0);
      ActionEvent actionEvent0 = new ActionEvent(requestListener0, 0, "", 0);
      // Undeclared exception!
      try { 
        requestListener0.actionPerformed(actionEvent0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // main.RequestListener cannot be cast to javax.swing.JButton
         //
         verifyException("main.RequestListener", e);
      }
  }

  @Test(timeout = 100000)
  public void test4()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      RequestListener requestListener0 = null;
      try {
        requestListener0 = new RequestListener(arrayList0, (-1));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.RequestListener", e);
      }
  }

  @Test(timeout = 100000)
  public void test5()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      RequestListener requestListener0 = new RequestListener(arrayList0, 0);
      Direction direction0 = Direction.DOWN;
      // Undeclared exception!
      try { 
        requestListener0.externalCall(0, direction0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("main.RequestListener", e);
      }
  }

  @Test(timeout = 100000)
  public void test6()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      RequestListener requestListener0 = new RequestListener(arrayList0, 3);
      requestListener0.run();
  }

  @Test(timeout = 100000)
  public void test7()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      RequestListener requestListener0 = new RequestListener(arrayList0, 0);
      Direction direction0 = Direction.UP;
      // Undeclared exception!
      try { 
        requestListener0.externalCall(0, direction0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("main.RequestListener", e);
      }
  }

  @Test(timeout = 100000)
  public void test8()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      RequestListener requestListener0 = new RequestListener(arrayList0, 0);
      // Undeclared exception!
      try { 
        requestListener0.internalCall(0, (Elevator) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.RequestListener", e);
      }
  }

  @Test(timeout = 100000)
  public void test9()  throws Throwable  {
      ArrayList<Elevator> arrayList0 = new ArrayList<Elevator>();
      RequestListener requestListener0 = new RequestListener(arrayList0, 0);
      requestListener0.run();
  }
}
